### ISSUE TITLE
The process of building is too complex & CI doesn't work

### ISSUE THREAD

**Issue by ehenoma** [java-sheets/java-sheets#12]
The current problems related to building:
- The build pipeline fails to connect to docker.
- Building the project requires a lot of knowledge 

We need to:
- Fix the pipeline and ensure that all images are only build by CI
- Add a single command to build the application

**Comment by Paul2708** [comment]
> The build pipeline fails to connect to docker.

I just ran the docker login action and everything worked fine. Can you ensure that you set the secrets?

> Add a single command to build the application

Do you refer to a single command that executes the required steps as in the pipeline to build the project?

**Comment by ehenoma** [comment]
> Do you refer to a single command that executes the required steps as in the pipeline to build the project?
I think it is totally fine and good to have multiple steps in the pipeline.
But devs should have a single command to run locally that does everything
from building the protocol (and related js packaging files) to the website and server.
It is pretty simple, could be a shell script even. But I think a gradle task would be better.

**Comment by ehenoma** [comment]
> I just ran the docker login action and everything worked fine. Can you ensure that you set the secrets?
https://github.com/java-sheets/java-sheets/runs/3746941097
I configured the secrets but I am gonna check that again in a short time
